#!/usr/bin/env python3
"""Create the repo-root .env for HOLD without the secrets passing through anyone else.

Prompts for the ClickHouse admin password with hidden input, generates strong passwords
for the hold_writer and hold_reader users, and writes .env. Refuses to overwrite an
existing .env unless --force. Prints variable names only, never values.

    .venv\\Scripts\\python scripts\\init_env.py --host <service-host>
"""

from __future__ import annotations

import argparse
import getpass
import secrets
import string
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SPECIALS = "-_.!@%^*"  # no quotes, '#', '$' or spaces: safe for hold/env.py and shells


def strong_password(length: int = 28) -> str:
    """Random password with upper, lower, digit and special (ClickHouse Cloud policy)."""
    alphabet = string.ascii_letters + string.digits + SPECIALS
    while True:
        pw = "".join(secrets.choice(alphabet) for _ in range(length))
        if (any(c.islower() for c in pw) and any(c.isupper() for c in pw)
                and any(c.isdigit() for c in pw) and any(c in SPECIALS for c in pw)):
            return pw


def normalize_host(raw: str) -> str:
    host = raw.strip()
    for prefix in ("https://", "http://"):
        if host.lower().startswith(prefix):
            host = host[len(prefix):]
    host = host.split("/", 1)[0].split(":", 1)[0]
    if not host or any(c in host for c in " @"):
        raise ValueError(f"not a hostname: {raw!r}")
    return host


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--host", required=True, help="ClickHouse Cloud service hostname (https:// and :8443 are stripped)")
    parser.add_argument("--admin-user", default="default")
    parser.add_argument("--out", default=str(REPO / ".env"))
    parser.add_argument("--force", action="store_true", help="overwrite an existing file")
    parser.add_argument("--admin-password-stdin", action="store_true",
                        help="read the admin password from stdin instead of a hidden prompt (for automation)")
    args = parser.parse_args()

    out = Path(args.out)
    if out.exists() and not args.force:
        print(f"refusing to overwrite {out} (use --force)", file=sys.stderr)
        return 2
    try:
        host = normalize_host(args.host)
    except ValueError as exc:
        print(exc, file=sys.stderr)
        return 2
    if args.admin_password_stdin:
        admin_pw = sys.stdin.readline().rstrip("\r\n").lstrip("﻿")  # PowerShell pipes add a BOM
    else:
        admin_pw = getpass.getpass(f"ClickHouse password for '{args.admin_user}' (input hidden): ")
    if not admin_pw:
        print("empty admin password; nothing written", file=sys.stderr)
        return 2

    values = {
        "CLICKHOUSE_HOST": host,
        "CLICKHOUSE_PORT": "8443",
        "CLICKHOUSE_SECURE": "1",
        "CLICKHOUSE_DATABASE": "default",
        "CLICKHOUSE_USER": "hold_writer",
        "CLICKHOUSE_PASSWORD": strong_password(),
        "CLICKHOUSE_READER_USER": "hold_reader",
        "CLICKHOUSE_READER_PASSWORD": strong_password(),
        "CLICKHOUSE_ADMIN_USER": args.admin_user,
        "CLICKHOUSE_ADMIN_PASSWORD": admin_pw,
        "HOLD_SEMGREP": "1",
    }
    body = "# Generated by scripts/init_env.py. Never commit this file.\n"
    body += "".join(f"{k}={v}\n" for k, v in values.items())
    out.write_text(body, encoding="utf-8")
    print(f"wrote {out}: {', '.join(values)}")
    print("next: .venv\\Scripts\\python scripts\\setup_clickhouse.py   (creates table + users, then runs the checks)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
